spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ${PASSWORD}
    url: jdbc:mysql://${HOST}:${PORT}/docker_use?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#  redis:
#    host: 81.69.227.238
#    port: 2672
#    password:
#    database: 0
server:
  port: 8081

mybatis:
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

